params:
  n_orientations: 30
  n_best_paths: 1
  n_flips: 1
  yaw_angles: [-100, -80, -60, -40, -20, 0, 20, 40, 60, 80, 100]
  radius_distances: [0, -2, -4, -6]
  deltahedron_sizes: [12]
  residues_per_helix: [8]
  loop_lengths: [8, 9, 10, 11, 12, 13]
  diffuse_termini: True # New

ligand:
  name: "heme"
  raw_file_path: "/home/tadas/code/deltaprot_heme_binder_design/heme/heme.pdb" 
  file_path: "/home/tadas/code/deltaprot_heme_binder_design/heme/heme_aligned.pdb" # will be generated
  radius_axis: y
  yaw_axis: z


directories:
  path_choice_output_dir: "/home/tadas/code/deltaprot_heme_binder_design/outputs_2/1_path_choices"
  assembly_output_dir: "/home/tadas/code/deltaprot_heme_binder_design/outputs_2/2_assemblies"
  rf_diffusion_outputs: "/home/tadas/code/deltaprot_heme_binder_design/outputs_2/3_diffusion"
  seq_pred_inputs: "/home/tadas/code/deltaprot_heme_binder_design/outputs_2/4_sequence_prediction/fixed_inputs"
  seq_pred_outputs: "/home/tadas/code/deltaprot_heme_binder_design/outputs_2/4_sequence_prediction/"
  str_pred_outputs: "/home/tadas/code/deltaprot_heme_binder_design/outputs_2/5_structure_prediction/"
  evaluation: "/home/tadas/code/deltaprot_heme_binder_design/outputs_2/6_evaluation"
  # analysis_output_dir: "pipeline_outputs/analysis/"
  # design_selection_1_dir: "pipeline_outputs/design_selection_1/"

install_dirs: 
  rf_diffusion: "/home/tadas/code/RFdiffusion"
  deltaProteins: "/home/tadas/deltaProteins" # repository root folder
  proteinmpnn: "/home/tadas/code/ProteinMPNN" # 
  # alphafold2: "/home/tadas/bin/alphafold2"
  # omegafold: "/home/tadas/bin/omegafold"